### ISSUE TITLE
Use official typescript-register

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/catberry-ts#16]
There is (will be) a reference to my fork of typescript-register. We need to experiment and maybe replace it with the official verison.

**Comment by ForNeVeR** [comment]
This was fixed by bf5f64a5e4fc44a2fd82e515dfa368dbe9184a85.

**Comment by rexim** [comment]
I had some problem with `"typescript-register": "^1.1.0"` on Linux because of the old node (0.10.something). On windows I have 0.12.4 and everything works fine.

**Comment by ForNeVeR** [comment]
Well, you could try 0.12 with nvm. Travis does not seem to have any problems.

**Comment by ForNeVeR** [comment]
Also I'll consider any solutions that would add 0.10 compatibility if you have some.

**Comment by rexim** [comment]
ok

**Comment by rexim** [comment]
Install 0.12 via nvm. Still the same problem:

```
npm run tsdef

> catberry-ts@0.0.0 tsdef /home/rexim/Programming/mine/catberry-ts
> gulp tsdef

[00:42:10] Failed to load external module typescript-register
[00:42:10] Failed to load external module typescript-require
/home/rexim/Programming/mine/catberry-ts/gulpfile.ts:4
import gulp = require('gulp');
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/home/rexim/Programming/mine/catberry-ts/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/home/rexim/Programming/mine/catberry-ts/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/home/rexim/Programming/mine/catberry-ts/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)

npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/home/rexim/.nvm/versions/node/v0.12.4/bin/node" "/home/rexim/.nvm/versions/node/v0.12.4/bin/npm" "run" "tsdef"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! catberry-ts@0.0.0 tsdef: `gulp tsdef`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the catberry-ts@0.0.0 tsdef script 'gulp tsdef'.
npm ERR! This is most likely a problem with the catberry-ts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp tsdef
npm ERR! You can get their info via:
npm ERR!     npm owner ls catberry-ts
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rexim/Programming/mine/catberry-ts/npm-debug.log
```

I'm starting to suspect that there is something wrong with my environment... I use Mint, btw:

```
lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 17 Qiana
Release:    17
Codename:   qiana
```

Don't know which Ubuntu version it corresponds to... Do you have any Ubuntu nearby? Could you please try to reproduce on it? I'll try to investigate what wrong on my side.

**Comment by ForNeVeR** [comment]
Thank you for the report, I Will investigate this.
22.06.2015 0:46 пользователь "Alexey Kutepov" notifications@github.com
написал:

**Comment by rexim** [comment]
I'd better create a separate issue for this
